export const imgData = [
  {
    name: "Space Walking",
    image: "/img1.svg",
    author: "Animatee",
    avatar: "/avatar1.svg",
    price: 2,
    id: 1,
    amount: 1,
  },
  {
    name: "Dog",
    image: "/img2.svg",
    author: "Shroke",
    avatar: "/avatar3.svg",
    price: 4,
    id: 2,
    amount: 1,
  },
  {
    name: "Magic Mushroom",
    image: "/img3.svg",
    author: "Snoke",
    avatar: "/avatar1.svg",
    price: 3,
    id: 3,
    amount: 1,
  },
  {
    name: "Galaxy",
    image: "/img4.svg",
    author: "Animakid",
    avatar: "/avatar3.svg",
    price: 1,
    id: 4,
    amount: 1,
  },
  {
    name: "Dream",
    image: "/img5.svg",
    author: "Nfts",
    avatar: "/avatar1.svg",
    price: 5,
    id: 5,
    amount: 1,
  },
  {
    name: "Woman",
    image: "/img6.svg",
    author: "Universe",
    avatar: "/avatar2.svg",
    price: 3,
    id: 6,
    amount: 1,
  },

  {
    name: "Cosmos",
    image: "/img7.svg",
    author: "Cutty",
    avatar: "/avatar1.svg",
    price: 3,
    id: 7,
    amount: 1,
  },
  {
    name: "Little girl",
    image: "/img8.svg",
    author: "Lee",
    avatar: "/avatar2.svg",
    price: 4,
    id: 8,
    amount: 1,
  },
  {
    name: "Space tales",
    image: "/img10.svg",
    author: "Animakid",
    avatar: "/avatar1.svg",
    price: 4,
    id: 9,
    amount: 1,
  },
  {
    name: "Sunset Dimension",
    image: "/img11.svg",
    author: "Animakid",
    avatar: "/avatar3.svg",
    price: 5,
    id: 10,
    amount: 1,
  },
  {
    name: "Designer Bear",
    image: "/img17.svg",
    author: "Orbition",
    avatar: "/avatar2.svg",
    price: 2,
    id: 11,
    amount: 1,
  },
  {
    name: "Dancing Robot",
    image: "/img18.svg",
    author: "Orbition",
    avatar: "/avatar1.svg",
    price: 3,
    id: 12,
    amount: 1,
  },
];

// export const Socials = [
//   {
//     name: "Discord",
//     src: "/instagram.svg",
//   },
//   {
//     name: "Facebook",
//     src: "/facebook.svg",
//   },
//   {
//     name: "Instagram",
//     src: "/discord.svg",
//   },
// ];
// export const Projects = [
//   {
//     title: "Modern Nextjs Website",
//     text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
//     src: "/NextWebsite.png",
//   },
//   {
//     title: "Space Themed Website",
//     text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
//     src: "/SpaceWebsite.png",
//   },
//   {
//     title: "Modern Nextjs Portfolio",
//     text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
//     src: "/WebPortfolio.png",
//   },
//   {
//     title: "Matrix themed Website",
//     text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
//     src: "/Matrix.png",
//   },
// ];
