import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import type { Metadata } from 'next'
import { Work_Sans  } from 'next/font/google'
import './globals.css'

const inter = Work_Sans({weight:'400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NFT Marketplace',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  )
}
